language: node_js
node_js:
 - 11.6.0
cache: npm

notifications:
  slack:
    on_success: always
    on_failure: always 
    on_start: always 
    on_cancel: always 
    on_error: always 

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: build
      script: npm run start